let PRODUCTS=[
{id:"1",name:"Primer alto sólidos 2K",category:"Preparación",description:"Formato 1L · Gris",price:18990,color:"#a9b4a6",tag:"PRIMER 2K",stock:10},
{id:"2",name:"Barniz acrílico 2K",category:"Terminación",description:"Formato 1L · Alto brillo",price:24990,color:"#e3e6d4",tag:"CLEAR 2K",stock:8},
{id:"3",name:"Masilla poliéster fina",category:"Preparación",description:"Formato 1kg · Secado rápido",price:8990,color:"#d49a5d",tag:"MASILLA",stock:20},
{id:"4",name:"Diluyente universal",category:"Pintura",description:"Formato 1L · Uso profesional",price:7990,color:"#a9b5a2",tag:"THINNER",stock:15},
{id:"5",name:"Base color blanco",category:"Pintura",description:"Formato 1L · Excelente cubritivo",price:16990,color:"#f0eee1",tag:"BASE",stock:9},
{id:"6",name:"Lija al agua surtida",category:"Herramientas",description:"Pack 10 unidades",price:4990,color:"#d08d52",tag:"P400",stock:30},
{id:"7",name:"Cinta enmascarar",category:"Herramientas",description:"Rollo 50m · 24mm",price:3990,color:"#d8b94a",tag:"TAPE",stock:24},
{id:"8",name:"Pasta de pulir fina",category:"Terminación",description:"Formato 500g · Acabado espejo",price:11990,color:"#d8d9ca",tag:"POLISH",stock:12}];
let cart=JSON.parse(localStorage.getItem("ea-cart")||"[]"),category="Todos";
const money=n=>new Intl.NumberFormat("es-CL",{style:"currency",currency:"CLP",maximumFractionDigits:0}).format(n);
const $=s=>document.querySelector(s);
function renderProducts(){const q=$("#search").value.toLowerCase(),list=PRODUCTS.filter(p=>(category==="Todos"||p.category===category)&&`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(q));$("#product-grid").innerHTML=list.map(p=>`<article class="product-card"><div class="product-image" style="--color:${p.color}"><span class="product-label">${p.tag}</span></div><div class="product-info"><h3>${p.name}</h3><p>${p.description}</p><div class="product-bottom"><b>${money(p.price)}</b><button class="add" data-add="${p.id}">+</button></div></div></article>`).join("");$("#empty-state").hidden=list.length>0}
function renderCart(){const items=cart.map(i=>({...PRODUCTS.find(p=>p.id===i.id),quantity:i.quantity})).filter(i=>i.id),qty=cart.reduce((n,i)=>n+i.quantity,0),total=items.reduce((n,i)=>n+i.price*i.quantity,0);$("#cart-count").textContent=qty;$("#floating-cart-count").textContent=qty;$("#floating-cart-total").textContent=money(total);$("#floating-cart").classList.toggle("visible",qty>0&&!$("#cart-drawer").classList.contains("open"));$("#cart-items").innerHTML=items.map(i=>`<div class="cart-item"><div class="cart-thumb" style="background:${i.color}">${i.tag}</div><div><h3>${i.name}</h3><small>${money(i.price)} c/u</small><div class="cart-controls"><button data-dec="${i.id}">−</button><span>${i.quantity}</span><button data-inc="${i.id}">+</button><button data-remove="${i.id}">×</button></div></div><b>${money(i.price*i.quantity)}</b></div>`).join("");$("#cart-total").textContent=money(total);$("#cart-empty").hidden=items.length>0;$("#drawer-footer").hidden=!items.length;localStorage.setItem("ea-cart",JSON.stringify(cart))}
function openCart(){$("#cart-overlay").hidden=false;$("#cart-drawer").classList.add("open");$("#cart-drawer").setAttribute("aria-hidden","false");$("#floating-cart").classList.remove("visible")}
function closeCart(){$("#cart-overlay").hidden=true;$("#cart-drawer").classList.remove("open");$("#cart-drawer").setAttribute("aria-hidden","true");renderCart()}
document.addEventListener("click",e=>{const add=e.target.closest("[data-add]");if(add){const i=cart.find(x=>x.id===add.dataset.add);i?i.quantity++:cart.push({id:add.dataset.add,quantity:1});renderCart();openCart()}const inc=e.target.closest("[data-inc]"),dec=e.target.closest("[data-dec]"),rem=e.target.closest("[data-remove]");if(inc||dec||rem){const id=(inc||dec||rem).dataset.inc||(inc||dec||rem).dataset.dec||(inc||dec||rem).dataset.remove, item=cart.find(x=>x.id===id);if(rem)cart=cart.filter(x=>x.id!==id);else if(item){item.quantity+=inc?1:-1;if(item.quantity<1)cart=cart.filter(x=>x.id!==id)}renderCart()}});
document.querySelectorAll(".category").forEach(b=>b.addEventListener("click",()=>{document.querySelector(".category.active").classList.remove("active");b.classList.add("active");category=b.dataset.category;renderProducts()}));$("#search").addEventListener("input",renderProducts);$("#open-cart").addEventListener("click",openCart);$("#floating-cart").addEventListener("click",openCart);$("#close-cart").addEventListener("click",closeCart);$("#cart-overlay").addEventListener("click",closeCart);document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCart()});
$("#checkout").addEventListener("click",async()=>{const payment=document.querySelector('input[name="payment"]:checked')?.value;if(payment==="mercadopago"){const name=prompt("Nombre completo:");const email=prompt("Correo electrónico:");if(!name||!email)return;const phone=prompt("Teléfono (opcional):")||"";const button=$("#checkout");button.disabled=true;button.textContent="Preparando pago...";try{const response=await fetch("/api/create-preference",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:{name,email,phone},items:cart})});const result=await response.json();if(!response.ok)throw new Error(result.error||"No se pudo iniciar el pago");window.location.href=result.checkoutUrl}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent="Continuar pedido ↗"}return}const lines=cart.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);return`• ${i.quantity} x ${p.name} (${money(p.price*i.quantity)})`});const total=cart.reduce((n,i)=>n+PRODUCTS.find(p=>p.id===i.id).price*i.quantity,0);const message=`Hola, Estudio Araucarias. Quiero hacer este pedido:\n\n${lines.join("\n")}\n\nTotal estimado: ${money(total)}\n\n¿Me confirman disponibilidad y datos para transferencia?`;window.open(`https://wa.me/56956327219?text=${encodeURIComponent(message)}`,"_blank")});
async function loadRemote(){if(!window.supabase||!window.SUPABASE_URL||!window.SUPABASE_ANON_KEY)return;const db=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY),{data,error}=await db.from("products").select("*").eq("active",true).order("created_at");if(!error&&data?.length)PRODUCTS=data.map(p=>({...p,price:p.price_clp}))}
loadRemote().finally(()=>{renderProducts();renderCart()});
